### ISSUE TITLE
Install apt-cacher-ng / polipo

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/dev-droplet#1]
So we can leverage @tmatilai's awesome [vagrant-proxyconf](https://github.com/tmatilai/vagrant-proxyconf)

**Comment by tmatilai** [comment]
The [apt](http://community.opscode.com/cookbooks/apt) community cookbook has a recipe to install apt-cacher-ng, and in [polipo-box](https://github.com/tmatilai/polipo-box/blob/master/Berksfile) I'm using [polipo_appliance](https://github.com/sandfish8/chef-polipo_appliance). With both you have to take care not to configure the machine to use the proxy server before it is installed. =)

Just ask if you need some help. I've played with both a bit. The basic installation is really straightforward though.

**Comment by fgrehm** [comment]
Cool, for sure I'll bug you in case something goes wrong :P
